spring.application.name=deliciousnessness
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/deliciousnessness
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
app.seed.username=${APP_SEED_USERNAME:}
app.seed.password=${APP_SEED_PASSWORD:}
# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
server.forward-headers-strategy=framework